baseURL = "https://dchou1618.github.io/aws-tuning-detection/"
languageCode = "en-us"
title = "AWS Tuning Detection"
[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"